# Generated by Django 5.2.3 on 2025-10-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('poster', models.URLField()),
                ('release_date', models.CharField(max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
